# version format
version: 2.3.1.{build}.0

os: Visual Studio 2015

artifacts:
  - path: 'build/doc/*.chm'
    name: chmDocs
  - path: 'build/doc/htmlDocs.zip'
    name: htmlDocs

install:
    - cmd: 7z x -y c:\projects\cpacs\development\3rdparty.zip -oc:\projects\cpacs\development\

platform: Any CPU

configuration: Release

build:
    project: documentation\Cpacs_doc_project.shfbproj

after_build:
  - cmd: 7z a -tzip build\doc\htmlDocs.zip build\doc\*
