"""Helpers for writing the CPACS example files generated by the figure scripts.

Every function returns XML as text starting at column 0 and indented by four
spaces per level, the form of the code examples in the schema documentation.
"""

from __future__ import annotations

from pathlib import Path

TIMESTAMP = "2026-09-15T12:00:00"  # fixed, so that repeated runs write identical files


def indent(text: str, levels: int) -> str:
    prefix = "    " * levels
    return "\n".join(prefix + line for line in text.splitlines())


def vector(values) -> str:
    return ";".join(f"{v:g}" for v in values)


def transformation_xml(rotation=(0.0, 0.0, 0.0), scaling=(1.0, 1.0, 1.0), translation=(0.0, 0.0, 0.0)) -> str:
    parts = ["<transformation>"]
    for name, values in (("rotation", rotation), ("scaling", scaling), ("translation", translation)):
        parts.append(f"    <{name}>")
        parts += [f"        <{axis}>{value:g}</{axis}>" for axis, value in zip("xyz", values, strict=True)]
        parts.append(f"    </{name}>")
    parts.append("</transformation>")
    return "\n".join(parts)


def write_cpacs_file(path: Path, generator: Path, name: str, description: str, model_uid: str, model_name: str,
                     components_tag: str, components: str, profiles_tag: str, profiles: str) -> None:
    """Write a complete CPACS file with one aircraft model and its profiles.

    generator is the script writing the file (pass Path(__file__)). It is named in a
    comment at the top of the file and in the version information, so that nobody
    edits the file by hand and loses the changes the next time the script runs.
    """
    script = generator.resolve().relative_to(path.resolve().parents[1]).as_posix()
    path.write_text(
        f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by {script}.
    Do not edit this file by hand, it is overwritten whenever the script runs.
    Change the script instead and run it from the repository root: uv run {script}
-->
<cpacs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/cpacs_schema.xsd">
    <header>
        <name>{name}</name>
        <description>{description}</description>
        <version>1.0.0</version>
        <versionInfos>
            <versionInfo version="1.0.0">
                <creator>DLR-SL</creator>
                <timestamp>{TIMESTAMP}</timestamp>
                <description>Generated by {script}</description>
                <cpacsVersion>3.5</cpacsVersion>
            </versionInfo>
        </versionInfos>
    </header>
    <vehicles>
        <aircraft>
            <model uID="{model_uid}">
                <name>{model_name}</name>
                <{components_tag}>
{indent(components, 5)}
                </{components_tag}>
            </model>
        </aircraft>
        <profiles>
            <{profiles_tag}>
{indent(profiles, 4)}
            </{profiles_tag}>
        </profiles>
    </vehicles>
</cpacs>""",
        encoding="utf-8",
        newline="\n",
    )
