"""Helpers for writing the CPACS example files generated by the figure scripts.

Every function returns XML as text starting at column 0 and indented by four
spaces per level, the form of the code examples in the schema documentation.
"""

from __future__ import annotations

from pathlib import Path

TIMESTAMP = "2026-09-15T12:00:00"  # fixed, so that repeated runs write identical files


def indent(text: str, levels: int) -> str:
    prefix = "    " * levels
    return "\n".join(prefix + line for line in text.splitlines())


def vector(values) -> str:
    return ";".join(f"{v:g}" for v in values)


def transformation_xml(rotation=(0.0, 0.0, 0.0), scaling=(1.0, 1.0, 1.0), translation=(0.0, 0.0, 0.0)) -> str:
    parts = ["<transformation>"]
    for name, values in (("rotation", rotation), ("scaling", scaling), ("translation", translation)):
        parts.append(f"    <{name}>")
        parts += [f"        <{axis}>{value:g}</{axis}>" for axis, value in zip("xyz", values, strict=True)]
        parts.append(f"    </{name}>")
    parts.append("</transformation>")
    return "\n".join(parts)


def _collections(pairs, levels: int) -> str:
    """<tag> ... </tag> blocks for (tag, content) pairs, the tags at the given level."""
    blocks = []
    for tag, content in pairs:
        blocks += [indent(f"<{tag}>", levels), indent(content, levels + 1), indent(f"</{tag}>", levels)]
    return "\n".join(blocks)


def write_cpacs_file(path: Path, generator: Path, name: str, description: str, model_uid: str | None, model_name: str,
                     components_tag: str | None, components: str, profiles_tag: str, profiles: str,
                     extra_components=(), extra_profiles=(), extra_vehicles=()) -> None:
    """Write a complete CPACS file with one aircraft model and its profiles.

    generator is the script writing the file (pass Path(__file__)). It is named in a
    comment at the top of the file and in the version information, so that nobody
    edits the file by hand and loses the changes the next time the script runs.

    extra_components and extra_profiles are further (tag, xml) pairs, written after
    the first component and profile collection. model_uid None writes no aircraft model,
    e.g. for data that belongs to no component. extra_vehicles are (tag, xml) pairs
    written after the profiles, e.g. structural elements and materials.
    """
    script = generator.resolve().relative_to(path.resolve().parents[1]).as_posix()
    components_pairs = [(components_tag, components)] if components_tag else []
    component_blocks = "\n" + _collections([*components_pairs, *extra_components], 4) if components_pairs or extra_components else ""
    profile_blocks = _collections([(profiles_tag, profiles), *extra_profiles], 3)
    vehicle_blocks = "\n" + _collections(extra_vehicles, 2) if extra_vehicles else ""
    aircraft_block = f"""
        <aircraft>
            <model uID="{model_uid}">
                <name>{model_name}</name>{component_blocks}
            </model>
        </aircraft>""" if model_uid else ""
    path.write_text(
        f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by {script}.
    Do not edit this file by hand, it is overwritten whenever the script runs.
    Change the script instead and run it from the repository root: uv run {script}
-->
<cpacs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/cpacs_schema.xsd">
    <header>
        <name>{name}</name>
        <description>{description}</description>
        <version>1.0.0</version>
        <versionInfos>
            <versionInfo version="1.0.0">
                <creator>DLR-SL</creator>
                <timestamp>{TIMESTAMP}</timestamp>
                <description>Generated by {script}</description>
                <cpacsVersion>3.5</cpacsVersion>
            </versionInfo>
        </versionInfos>
    </header>
    <vehicles>{aircraft_block}
        <profiles>
{profile_blocks}
        </profiles>{vehicle_blocks}
    </vehicles>
</cpacs>""",
        encoding="utf-8",
        newline="\n",
    )
