name: Generate CPACS Libs

on:
  push:
    branches:
      - develop

jobs:
  generate-python-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10' 

      - name: Install generateDS
        run: |
          pip install generateds
          pip install lxml

      - name: Generate CPACS Python Classes
        run: |
          generateDS.py -o cpacsLib.py -f ./schema/cpacs_schema.xsd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpacsPythonLib
          path: cpacsLib.py
          
  generate-java-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and Install xjc
        run: |
          wget https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-ri/2.3.1/jaxb-ri-2.3.1.zip
          unzip jaxb-ri-2.3.1.zip
          chmod +x jaxb-ri/bin/xjc.bat
          export PATH="$PATH:$GITHUB_WORKSPACE/jaxb-ri-2.3.1/bin"

      - name: Generate Java Classes
        run: |
          xsd_file_path="./schema/cpacs_schema.xsd"
          mkdir .buildjavaLib
          xjc -d .\build\javaLib "$xsd_file_path"

      - name: Upload Java Classes Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpacsJavaLib
          path: .\build\javaLib\generated
