name: run_examples_validation.yml
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: false
    - run: |
          conda info
          conda list
    - run: conda create -n myenv python=3.9
    - run: conda activate myenv
    - run: conda install pytest lxml tixi3 -c dlr-sc
    - run: pytest
