name: Validate example files
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: false
        
    - name: Create new conda environment
      run: |
        conda create -n cpacs python=3.9
      
    - name: Activate new conda environment
      run: |
        conda activate cpacs

    - name: Install python modules
      run: |
        conda install pytest lxml tixi3 -c dlr-sc

    - name: Run pytest
      run: |
        pytest
