name: run_examples_validation.yml
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    - run: conda --version
    - run: which python
    - run: conda install lxml tixi3 -c dlr-sc
    - run: pytest
